# For more info on HTTP files go to https://aka.ms/vs/httpfile
GET https://localhost:9081/manage/info
Accept: application/json
Authorization: Bearer CfDJ8MbDOyLS0ItMpwVlV9XzUSe4c3y3h_9KfCTqtIO4sf-IIDYnZWCh4TMy72WWPA9ea_We8XoHxVFGd-78eqlAxL6x6XcLESkvEZldYmpVUJ3n-LtVZJkRJjDZeusv3SOEbH3lxpeCNE2w4bNXGNWVaxbP3Ix4u2IbxBRWUwtJih7uryHu1xgvYewj7YjvsHv6DMkGCqjsE2QL7_8zWggk_GRmmNmqsVV8g38NIzWHh-Wg_Z_1YKF-7oLwY6DHoyp-lRwtCklwXo1b5DN9EMVe9HSajLttFNNhA1kK61BtOBhdRORdUOaEg3_BWyO3aNI5yfxQuVlX7Z1y5qaC3B4NlSkhimzdmQhSsigmI4tQYgA0CAd3qRMytwjLQMoMvNHny8GFVT7slzce0z4D4-LiWUBdWERdDXPaPL3d5-YaldtvmPQoVPGHqaYFABzqNq_NvxKQF4gdiirqOSLPc_zUEP2GxrzudrBm6zToFHl27OHr6WfebuBHOrIGZIgvSGH22uPsX9F8eDpqurAPoaH28LM2QXO4s9zshD7EFZkb6L_I2tz5TlaQ9DU3CPMC0Zpk-qm-ezZY649Z_nFGF_tg5vvjX8-2oepLLzyPYJ-MmY6xPlyFFdnlMNhMKsj87ZPSvh58OxLkiw2QYPnC4rH4TwaJAKdAYbbiqMOKxNttT4r502cwYRSiDbEZmUSmmEKyb6ef1OGYxruEpFneDGpMPIhZZNCFlVulv_zbv9fNbtN2EWs6LT8uCAIRySjkktAeig7PcFSRUajo-2yjr5JwA6px29ub_lMPasJyZsz0JMVWntlYeQRed79PPofWAH2DDg